# Read the Docs configuration file for Sphinx
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"  # Using a more stable Python version for docs

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally declare the Python requirements required to build your documentation
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs
