name: Feature request
description: Suggest an idea or improvement for ApiLinker
title: "feat: <concise title>"
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve ApiLinker!

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem are you trying to solve? What’s the context?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed solution or API. Include examples if relevant.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: This feature would be useful to more than one user
        - label: I’m willing to help implement this feature

